In [4]:
import numpy as np

In [5]:
#np.hstack => horizontal stack

In [6]:
#np.vstack => vertical stack

In [11]:
A = np.round(10*np.random.rand(2,3)) #rand(2,3) => 3 elemanlı 2 tane array oluşturdu

In [12]:
A

array([[0., 1., 9.],
       [2., 5., 3.]])

In [13]:
A+3 #tüm elemenların 3 ile toplanmasını sağladık

array([[ 3.,  4., 12.],
       [ 5.,  8.,  6.]])

In [17]:
A+(np.arange(2).reshape(2,1))

array([[0., 1., 9.],
       [3., 6., 4.]])

In [18]:
A

array([[0., 1., 9.],
       [2., 5., 3.]])

In [19]:
B = np.round(10*np.random.rand(2,2)) 

In [20]:
B

array([[ 4., 10.],
       [ 1.,  7.]])

In [21]:
C = np.hstack((A,B)) 
#must be tuple inside hstack
#hstack iki arrayin yatay olarak birleşmesini sağlar
#hstack için sütun satır eşitsizliği önemli değildir.

In [22]:
C

array([[ 0.,  1.,  9.,  4., 10.],
       [ 2.,  5.,  3.,  1.,  7.]])

In [24]:
D = np.round(10*np.random.rand(2,2))

In [25]:
E = np.vstack((B,D)) 
#eğer arraylerden biri 2x3 diğeri 2x2 ise vstack çalışmaz aynı sütun sayıısına sahip olmalı 
#arrayler 2x3 3x3 şeklindeyse vstack çalışır. Burada önemli olan sütün sayısının eşit olmasıdır.

In [26]:
E

array([[ 4., 10.],
       [ 1.,  7.],
       [ 9.,  5.],
       [ 9.,  5.]])

In [27]:
F = np.round(10*np.random.rand(3,3))

In [28]:
G = np.vstack((A,F))

In [29]:
G 

array([[0., 1., 9.],
       [2., 5., 3.],
       [6., 9., 8.],
       [2., 3., 7.]])

In [33]:
H = np.hstack((D,F))

In [34]:
H

array([[9., 5., 6., 9., 8.],
       [9., 5., 2., 3., 7.]])

In [35]:
shuf = np.random.permutation(np.arange(10)) #10 elemanlı bir array oluşturuldu.

In [36]:
shuf

array([1, 7, 8, 0, 9, 3, 6, 4, 5, 2])

In [39]:
shuf.sort() #sort() fonksiyonu arrayi küçükten büyüğe sıralamamızı sağlar.

In [40]:
shuf

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
#we can also use sort func like that;
np.sort(shuf)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
shuf = shuf[::-1] #en sondaki elemandan başlayarak ilk elemana kadar gider bu sayede arrayi tersten sıralamış olur

In [43]:
shuf

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [44]:
B = np.array(['zeynep', 'dilara', 'şimşek', '23dilara', 'sissoylu'])

In [45]:
np.sort(B) #string ifadeler alfabe sıralarına göre sıralanırlar

array(['23dilara', 'dilara', 'sissoylu', 'zeynep', 'şimşek'], dtype='<U8')