In [1]:
import numpy as np

In [2]:
a = np.zeros(3) #sıfırlardan oluşan 1D array oluşturur.

In [3]:
print(a)

[0. 0. 0.]


In [5]:
b = np.arange(15) #15 elemanlı 1D array oluşturur. 
#Belli bir sayıdan başlamasını istiyorsak arange(5,10) => 5'ten başlayıp 15-1'e gidecek
#artış sayısını belirlemek için 3. parametre ekleyebiliriz. arange(5,15,3) => üçer üçer artacak
#for i in range(5,15,3)

In [6]:
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
b = np.random.permutation(np.arange(10))
#np.arange(10) 0dan 9'a kadar array oluşturuyor, random.permutation da bunları karıştırmayı sağlıyor.

In [8]:
print(b)

[4 5 6 8 9 0 1 7 2 3]


In [9]:
c = np.random.randint(10,20) 
#10-20 arasında rastgele bir sayı döndürür
#c'nin tipi integer

In [10]:
print(c)

18


In [11]:
type(c)

int

In [12]:
d = np.random.rand(50) #50 elemanlı bir array oluşturdu ve tüm değerler 0-1 aralığında

In [13]:
print(d)

[0.16498379 0.70227475 0.19125863 0.29577831 0.09993215 0.42030158
 0.03560743 0.11923465 0.07005898 0.96039095 0.4408755  0.93493592
 0.283161   0.00577458 0.0283977  0.72732066 0.64162766 0.84808765
 0.76121211 0.88450072 0.70773805 0.67241211 0.86010655 0.36449496
 0.50317807 0.7614786  0.07494542 0.16032772 0.0800858  0.36508369
 0.24217342 0.48465033 0.04218723 0.40071182 0.05876065 0.36584911
 0.99142104 0.98389616 0.34292721 0.34501306 0.24146319 0.59933255
 0.31005826 0.15769274 0.72725004 0.55512218 0.55597266 0.86005446
 0.86289401 0.88343374]


In [14]:
e = np.random.rand(2,3) #2 array, 3 elements for each array

In [15]:
e

array([[0.85106167, 0.29454406, 0.87849847],
       [0.79673966, 0.09385989, 0.06043749]])

In [16]:
e.ndim

2

In [17]:
e = np.random.rand(2,3,4,2) 
#3D array = 2
#2D array = 3 for each 3D
#1D array = 4 for each 2D
#for each 1D array 2 elements inside

In [18]:
e

array([[[[0.25193312, 0.93272709],
         [0.91101957, 0.74942791],
         [0.50243604, 0.08758709],
         [0.69220159, 0.71035787]],

        [[0.77445222, 0.83373634],
         [0.96717343, 0.32494649],
         [0.85686098, 0.36289322],
         [0.13852568, 0.20532129]],

        [[0.50251036, 0.0524409 ],
         [0.01190968, 0.81469879],
         [0.01560526, 0.03708123],
         [0.11531951, 0.89783591]]],


       [[[0.95413499, 0.39710047],
         [0.25381829, 0.55961628],
         [0.72965037, 0.89258649],
         [0.16959989, 0.56061472]],

        [[0.75597723, 0.63753552],
         [0.05946477, 0.81554099],
         [0.47124696, 0.93002262],
         [0.91130032, 0.72057705]],

        [[0.97312612, 0.93601529],
         [0.81432109, 0.38083637],
         [0.58994233, 0.70241432],
         [0.79761338, 0.26957677]]]])

In [19]:
e.ndim

4

In [20]:
f = np.arange(100).reshape(4,25) #100 elemanlı arrayi 4x25'lik matrixe dönüştürdü.

In [21]:
f.shape

(4, 25)